In [2]:
import pandas as pd

In [3]:
pd.__version__

'1.5.1'

In [4]:
df = pd.read_csv('housing.csv')

In [5]:
df.size

206400

In [6]:
df.shape

(20640, 10)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [8]:
missing_values = df.isnull()

missing_counts = missing_values.sum()

print(missing_counts[missing_counts > 0].index.tolist()) #credits to internet

['total_bedrooms']


In [11]:
print(df['ocean_proximity'].unique())

['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']


In [16]:
df_filtered = df[df['ocean_proximity'] == 'NEAR BAY']

In [17]:
df_filtered

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
19067    -122.45     38.28                20.0       3306.0           503.0   
19068    -122.47     38.29                14.0       3732.0           846.0   
19069    -122.45     38.27                25.0       5024.0           881.0   
19077    -122.49     38.27                 8.0       5092.0           988.0   
19104    -122.51     38.17                 8.0       5875.0          1115.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
19067      1374.0       460.0         5.7984            297600.0   
19068      1277.0       775.0         2.5658            208000.0   
19069      1994.0       838.0         4.2237            262300.0   
19077      1657.0       936.0         3.5625            213200.0   
19104      2808.0      1029.0         3.6392            246300.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
19067        NEAR BAY  
19068        NEAR BAY  
19069        NEAR BAY  
19077        NEAR BAY  
19104        NEAR BAY  

[2290 rows x 10 columns]

In [18]:
average_price = df_filtered['median_house_value'].mean()

In [19]:
print(average_price)

259212.31179039303


In [29]:
average_bedrooms = df['total_bedrooms'].mean()

In [30]:
average_bedrooms

537.8705525375618

In [31]:
new_df = df.fillna(average_bedrooms)

In [32]:
average_bedrooms1 = new_df['total_bedrooms'].mean()

In [33]:
average_bedrooms1

537.8705525375617

In [34]:
df_island = df[df['ocean_proximity'] == 'ISLAND']

In [35]:
df_island = df_island[['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [36]:
df_island

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [37]:
np_array = df_island.to_numpy()

print(np_array)

[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]


In [38]:
import numpy as np

In [47]:
C = np.matmul(np_array.T, np_array)
print(C)

[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]


In [48]:
print(np.linalg.inv(C))

[[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]


In [49]:
W = np.linalg.inv(C)

In [50]:
list1 = [950, 1300, 800, 1000, 1300]
array1 = np.array(list1)

ValueError: operands could not be broadcast together with shapes (5,5) (3,5) 

In [51]:
AB = np.matmul(W, np_array.T)

In [52]:
AB

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [53]:
AC = np.matmul(AB, array1)

In [54]:
AC

array([23.12330961, -1.48124183,  5.69922946])